const DOM = {
    gameArea: document.getElementById('game-area'),
    uiArea: document.getElementById('ui-area'),
    gameCanvas: document.getElementById('game-canvas'),
    lanesContainer: document.getElementById('lanes-container'),
    scoreEl: document.getElementById('score'),
    comboEl: document.getElementById('combo'),
    judgementTextEl: document.getElementById('judgement-text'),
    comboTextEl: document.getElementById('combo-text'),
    musicPlayer: AudioEngine, // Web Audio API 기반 AudioEngine (지연 최소화를 위해 <audio> 엘리먼트 대체)
    countdownTextEl: document.getElementById('countdown-text'),
    noteCountContainer: document.getElementById('note-count-container'),
    noteCountInput: document.getElementById('note-count-input'),
    difficultyControls: document.getElementById('difficulty-controls'),
    musicModeControls: document.getElementById('music-mode-controls'),
    chartFileNameEl: document.getElementById('chart-file-name'),
    musicFileNameEl: document.getElementById('music-file-name'),
    requiredMusicFileNameEl: document.getElementById('required-music-file-name'),
    screens: {
        menu: document.getElementById('menu-screen'),
        practice: document.getElementById('practice-screen'),
        playing: document.getElementById('playing-screen'),
        result: document.getElementById('result-screen'),
        editorHome: document.getElementById('editor-home-screen'),
        editorSong: document.getElementById('editor-song-screen'),
        editor: document.getElementById('editor-screen'),
        settings: document.getElementById('settings-screen'),
        online: document.getElementById('online-screen'),
    },
    messages: {
        menu: document.getElementById('menu-message'),
        editor: document.getElementById('editor-message'),
        editorSong: document.getElementById('editor-song-message'),
        settings: document.getElementById('settings-message'),
    },
    difficulty: {
        toggleBtn: document.getElementById('toggle-details-btn'),
        toggleIcon: document.querySelector('#toggle-details-btn svg'),
        detailsPanel: document.getElementById('detailed-difficulty-settings'),
        fallSpeedSlider: document.getElementById('note-fall-speed-slider'),
        fallSpeedValue: document.getElementById('note-fall-speed-value'),
        spawnSpeedSlider: document.getElementById('note-spawn-speed-slider'),
        spawnSpeedValue: document.getElementById('note-spawn-speed-value'),
        dongtaSlider: document.getElementById('dongta-prob-slider'),
        dongtaValue: document.getElementById('dongta-prob-value'),
        maxSimultaneousSlider: document.getElementById('max-simultaneous-slider'),
        maxSimultaneousValue: document.getElementById('max-simultaneous-value'),
        dongtaTapProbSlider: document.getElementById('dongta-tap-prob-slider'),
        dongtaTapProbValue: document.getElementById('dongta-tap-prob-value'),
        dongtaLongProbSlider: document.getElementById('dongta-long-prob-slider'),
        dongtaLongProbValue: document.getElementById('dongta-long-prob-value'),
        dongtaFalseProbSlider: document.getElementById('dongta-false-prob-slider'),
        dongtaFalseProbValue: document.getElementById('dongta-false-prob-value'),
        longNoteSlider: document.getElementById('long-note-prob-slider'),
        longNoteValue: document.getElementById('long-note-prob-value'),
        falseNoteToggle: document.getElementById('false-note-toggle'),
        falseNoteProbContainer: document.getElementById('false-note-prob-container'),
        falseNoteProbSlider: document.getElementById('false-note-prob-slider'),
        falseNoteProbValue: document.getElementById('false-note-prob-value'),
    },
    finalScoreEl: document.getElementById('final-score'),
    rankEl: document.getElementById('rank'),
    finalPerfectEl: document.getElementById('final-perfect'),
    finalGoodEl: document.getElementById('final-good'),
    finalBadEl: document.getElementById('final-bad'),
    finalMissEl: document.getElementById('final-miss'),
    editor: {
        container: document.getElementById('editor-container'),
        timeline: document.getElementById('editor-timeline'),
        gridContainer: document.getElementById('editor-grid-container'),
        notesContainer: document.getElementById('editor-notes-container'),
        playhead: document.getElementById('editor-playhead'),
        
        // 상단 컨트롤
        audioFileInput: document.getElementById('audio-file-input-editor'),
        audioFileNameEl: document.getElementById('audio-file-name-editor'),
        startTimeInput: document.getElementById('editor-start-time'),
        previewLanesSelector: document.getElementById('editor-preview-lanes'),
        bpmInput: document.getElementById('bpm-input'),
        noteFallSpeedInput: document.getElementById('editor-note-fall-speed'),
        snapSelector: document.getElementById('editor-snap-selector'),
        addMeasureBtn: document.getElementById('editor-add-measure-btn'),
        removeMeasureBtn: document.getElementById('editor-remove-measure-btn'),
        noteTypeSelector: document.getElementById('editor-note-type-selector'),
        
        // 관리 버튼
        playBtn: document.getElementById('editor-play-btn'),
        stopBtn: document.getElementById('editor-stop-btn'),
        chartFilenameInput: document.getElementById('editor-chart-filename'),
        quickSaveBtn: document.getElementById('editor-quick-save-btn'),
        resetBtn: document.getElementById('editor-reset-btn'),
        backBtn: document.getElementById('editor-back-btn'),
        backToSongBtn: document.getElementById('editor-back-to-song-btn'),
        uploadBtn: document.getElementById('editor-upload-btn'), // Phase 3e: HTML에서 제거됨, null로 남음 (Editor._updateCloudUI가 null 체크함)
        cloudStatusEl: document.getElementById('editor-cloud-status'), // 위와 동일

        // 기타 UI
        statusLabel: document.getElementById('editor-status-label'),
        dirtyIndicator: document.getElementById('editor-dirty-indicator'),
    },
    // ── Phase 3: 종합 창 (노래 메타 + 난이도 목록) ──────────────────────────
    editorSong: {
        titleInput: document.getElementById('editor-song-title-input'),
        artistInput: document.getElementById('editor-song-artist-input'),
        audioFileInput: document.getElementById('editor-song-audio-input'),
        audioNameEl: document.getElementById('editor-song-audio-name'),
        beatmapList: document.getElementById('editor-song-beatmap-list'),
        addBeatmapBtn: document.getElementById('editor-song-add-beatmap-btn'),
        saveLocalBtn: document.getElementById('editor-song-save-local-btn'),
        loadLocalInput: document.getElementById('editor-song-load-local-input'),
        titleHeading: document.getElementById('editor-song-title'),
        uploadCloudBtn: document.getElementById('editor-song-upload-cloud-btn'),
    },
    // ── Phase 3d: 에디터 홈 (내 노래 클라우드 목록) ──────────────────────────
    editorHome: {
        songList: document.getElementById('editor-home-song-list'),
    },
    pauseGameBtn: document.getElementById('pause-game-btn'),
    resumeGameBtn: document.getElementById('resume-game-btn'),
    playingStatusLabel: document.getElementById('playing-status-label'),
    debugOverlay: document.getElementById('debug-overlay'),
    debugTitle: document.querySelector('#debug-overlay .title'),
    debugPerfContainer: document.getElementById('debug-perf-container'),
    debugStateContainer: document.getElementById('debug-state-container'),
    debugLogContainer: document.getElementById('debug-log-container'),
    settings: {
        iconMenu: document.getElementById('settings-icon-menu'),
        iconPlaying: document.getElementById('settings-icon-playing'),
        backBtn: document.getElementById('settings-back-btn'),
        tabsContainer: document.getElementById('settings-tabs'),
        tabContents: document.querySelectorAll('.tab-content'),
        musicVolumeSlider: document.getElementById('volume-slider-music'),
        musicVolumeValue: document.getElementById('volume-value-music'),
        sfxVolumeSlider: document.getElementById('volume-slider-sfx'),
        sfxVolumeValue: document.getElementById('volume-value-sfx'),
        debugModeToggle: document.getElementById('debug-mode-toggle'),
        controls: {
            keybindBoxes: document.querySelectorAll('.keybind-box'),
            statusLabel: document.getElementById('keybind-status-label'),
            saveBtn: document.getElementById('save-keybinds-btn')
        }
    },
    triggerModal: {
        container: document.getElementById('trigger-modal'),
        bpmInput: document.getElementById('trigger-bpm'),
        fallSpeedInput: document.getElementById('trigger-fall-speed'),
        transitionInput: document.getElementById('trigger-transition'),
        confirmBtn: document.getElementById('trigger-confirm-btn'),
        cancelBtn: document.getElementById('trigger-cancel-btn')
    }
};