const DOM = {
    gameArea: document.getElementById('game-area'),
    uiArea: document.getElementById('ui-area'),
    panelToggleBtn: document.getElementById('panel-toggle-btn'),
    gameCanvas: document.getElementById('game-canvas'),
    lanesContainer: document.getElementById('lanes-container'),
    scoreEl: document.getElementById('score'),
    comboEl: document.getElementById('combo'),
    hudTimeEl: document.getElementById('game-hud-time'),
    hudAccuracyEl: document.getElementById('game-hud-accuracy'),
    hudRankEl: document.getElementById('game-hud-rank'),
    spectateHudEl: document.getElementById('mp-spectate-hud'),
    judgementTextEl: document.getElementById('judgement-text'),
    comboTextEl: document.getElementById('combo-text'),
    musicPlayer: AudioEngine, // Web Audio API 기반 AudioEngine (지연 최소화를 위해 <audio> 엘리먼트 대체)
    countdownTextEl: document.getElementById('countdown-text'),
    noteCountContainer: document.getElementById('note-count-container'),
    noteCountInput: document.getElementById('note-count-input'),
    difficultyControls: document.getElementById('difficulty-controls'),
    musicModeControls: document.getElementById('music-mode-controls'),
    chartFileNameEl: document.getElementById('chart-file-name'),
    musicFileNameEl: document.getElementById('music-file-name'),
    requiredMusicFileNameEl: document.getElementById('required-music-file-name'),
    screens: {
        menu: document.getElementById('menu-screen'),
        practice: document.getElementById('practice-screen'),
        playing: document.getElementById('playing-screen'),
        result: document.getElementById('result-screen'),
        editorHome: document.getElementById('editor-home-screen'),
        editorSong: document.getElementById('editor-song-screen'),
        editor: document.getElementById('editor-screen'),
        settings: document.getElementById('settings-screen'),
        online: document.getElementById('online-screen'),
        multiplayer: document.getElementById('multiplayer-screen'),
        osuConvert: document.getElementById('osu-convert-screen'),
        calibration: document.getElementById('calibration-screen'),
    },
    messages: {
        menu: document.getElementById('menu-message'),
        editor: document.getElementById('editor-message'),
        editorSong: document.getElementById('editor-song-message'),
        settings: document.getElementById('settings-message'),
        osuConvert: document.getElementById('osu-convert-message'),
    },
    difficulty: {
        toggleBtn: document.getElementById('toggle-details-btn'),
        toggleIcon: document.querySelector('#toggle-details-btn svg'),
        detailsPanel: document.getElementById('detailed-difficulty-settings'),
        fallSpeedSlider: document.getElementById('note-fall-speed-slider'),
        fallSpeedValue: document.getElementById('note-fall-speed-value'),
        spawnSpeedSlider: document.getElementById('note-spawn-speed-slider'),
        spawnSpeedValue: document.getElementById('note-spawn-speed-value'),
        dongtaSlider: document.getElementById('dongta-prob-slider'),
        dongtaValue: document.getElementById('dongta-prob-value'),
        maxSimultaneousSlider: document.getElementById('max-simultaneous-slider'),
        maxSimultaneousValue: document.getElementById('max-simultaneous-value'),
        dongtaTapProbSlider: document.getElementById('dongta-tap-prob-slider'),
        dongtaTapProbValue: document.getElementById('dongta-tap-prob-value'),
        dongtaLongProbSlider: document.getElementById('dongta-long-prob-slider'),
        dongtaLongProbValue: document.getElementById('dongta-long-prob-value'),
        dongtaFalseProbSlider: document.getElementById('dongta-false-prob-slider'),
        dongtaFalseProbValue: document.getElementById('dongta-false-prob-value'),
        longNoteSlider: document.getElementById('long-note-prob-slider'),
        longNoteValue: document.getElementById('long-note-prob-value'),
        falseNoteToggle: document.getElementById('false-note-toggle'),
        falseNoteProbContainer: document.getElementById('false-note-prob-container'),
        falseNoteProbSlider: document.getElementById('false-note-prob-slider'),
        falseNoteProbValue: document.getElementById('false-note-prob-value'),
    },
    finalScoreEl: document.getElementById('final-score'),
    rankEl: document.getElementById('rank'),
    finalPerfectEl: document.getElementById('final-perfect'),
    finalGoodEl: document.getElementById('final-good'),
    finalBadEl: document.getElementById('final-bad'),
    finalMissEl: document.getElementById('final-miss'),
    finalAccuracyEl: document.getElementById('final-accuracy'),
    finalMaxComboEl: document.getElementById('final-max-combo'),
    finalEarlyLateEl: document.getElementById('final-early-late'),
    editor: {
        container: document.getElementById('editor-container'),
        seekGutter: document.getElementById('editor-seek-gutter'),
        timeline: document.getElementById('editor-timeline'),
        gridContainer: document.getElementById('editor-grid-container'),
        notesContainer: document.getElementById('editor-notes-container'),
        playhead: document.getElementById('editor-playhead'),
        timingStartMarker: document.getElementById('editor-timing-start-marker'),
        
        // 상단 컨트롤
        // audioFileInput/audioDropzone: 개별 비트맵 창의 "음악 불러오기" 버튼은 제거됨
        // (음악 로딩은 이제 종합 창 EditorSong에서만 관리). audioFileNameEl은 현재 로드된
        // 음악 파일명을 보여주는 정보 표시로만 남아있다.
        audioFileNameEl: document.getElementById('audio-file-name-editor'),
        startTimeInput: document.getElementById('editor-start-time'),
        timingStartInput: document.getElementById('editor-timing-start-input'),
        previewLanesSelector: document.getElementById('editor-preview-lanes'),
        bpmInput: document.getElementById('bpm-input'),
        noteFallSpeedInput: document.getElementById('editor-note-fall-speed'),
        useCustomFallSpeedToggle: document.getElementById('editor-use-custom-fallspeed-toggle'),
        snapSelector: document.getElementById('editor-snap-selector'),
        addMeasureBtn: document.getElementById('editor-add-measure-btn'),
        removeMeasureBtn: document.getElementById('editor-remove-measure-btn'),
        noteTypeSelector: document.getElementById('editor-note-type-selector'),
        toolSelector: document.getElementById('editor-tool-selector'),
        deleteSelectedBtn: document.getElementById('editor-delete-selected-btn'),
        
        // 관리 버튼
        playBtn: document.getElementById('editor-play-btn'),
        stopBtn: document.getElementById('editor-stop-btn'),
        chartFilenameInput: document.getElementById('editor-chart-filename'),
        quickSaveBtn: document.getElementById('editor-quick-save-btn'),
        resetBtn: document.getElementById('editor-reset-btn'),
        backToSongBtn: document.getElementById('editor-back-to-song-btn'),
        uploadBtn: document.getElementById('editor-upload-btn'), // Phase 3e: HTML에서 제거됨, null로 남음 (Editor._updateCloudUI가 null 체크함)
        cloudStatusEl: document.getElementById('editor-cloud-status'), // 위와 동일

        // 기타 UI
        statusLabel: document.getElementById('editor-status-label'),
        dirtyIndicator: document.getElementById('editor-dirty-indicator'),
    },
    // ── Phase 3: 종합 창 (노래 메타 + 난이도 목록) ──────────────────────────
    editorSong: {
        infoCardDropzone: document.getElementById('editor-song-info-card'),
        titleInput: document.getElementById('editor-song-title-input'),
        artistInput: document.getElementById('editor-song-artist-input'),
        audioFileInput: document.getElementById('editor-song-audio-input'),
        audioNameEl: document.getElementById('editor-song-audio-name'),
        coverFileInput: document.getElementById('editor-song-cover-input'),
        coverNameEl: document.getElementById('editor-song-cover-name'),
        previewStartInput: document.getElementById('editor-song-preview-start-input'),
        startTimeInput: document.getElementById('editor-song-start-time-input'),
        timingStartInput: document.getElementById('editor-song-timing-start-input'),
        beatmapList: document.getElementById('editor-song-beatmap-list'),
        addBeatmapBtn: document.getElementById('editor-song-add-beatmap-btn'),
        saveLocalBtn: document.getElementById('editor-song-save-local-btn'),
        loadLocalInput: document.getElementById('editor-song-load-local-input'),
        titleHeading: document.getElementById('editor-song-title'),
        readonlyBanner: document.getElementById('editor-song-readonly-banner'),
        uploadCloudBtn: document.getElementById('editor-song-upload-cloud-btn'),
        saveDraftBtn: document.getElementById('editor-song-save-draft-btn'),
        cloudStatusEl: document.getElementById('editor-song-cloud-status'),
    },
    // ── Phase 3d: 에디터 홈 (내 노래 클라우드 목록) ──────────────────────────
    editorHome: {
        songList: document.getElementById('editor-home-song-list'),
    },
    // ── 베타: osu!mania .osu → TheBeat 채보 변환 화면 ──────────────────────
    osuConvert: {
        fileInput: document.getElementById('osu-convert-file-input'),
        fallSpeedSlider: document.getElementById('osu-convert-fall-speed-slider'),
        fallSpeedValue: document.getElementById('osu-convert-fall-speed-value'),
        resultList: document.getElementById('osu-convert-result-list'),
        importBtn: document.getElementById('osu-convert-import-btn'),
        backBtn: document.getElementById('osu-convert-back-btn'),
    },
    pauseGameBtn: document.getElementById('pause-game-btn'),
    resumeGameBtn: document.getElementById('resume-game-btn'),
    playingStatusLabel: document.getElementById('playing-status-label'),
    debugOverlay: document.getElementById('debug-overlay'),
    debugTitle: document.querySelector('#debug-overlay .title'),
    debugPerfContainer: document.getElementById('debug-perf-container'),
    debugStateContainer: document.getElementById('debug-state-container'),
    debugLogContainer: document.getElementById('debug-log-container'),
    settings: {
        iconMenu: document.getElementById('settings-icon-menu'),
        iconPlaying: document.getElementById('settings-icon-playing'),
        backBtn: document.getElementById('settings-back-btn'),
        tabsContainer: document.getElementById('settings-tabs'),
        tabContents: document.querySelectorAll('.tab-content'),
        musicVolumeSlider: document.getElementById('volume-slider-music'),
        musicVolumeValue: document.getElementById('volume-value-music'),
        sfxVolumeSlider: document.getElementById('volume-slider-sfx'),
        sfxVolumeValue: document.getElementById('volume-value-sfx'),
        gameplayImageOpacitySlider: document.getElementById('gameplay-image-opacity-slider'),
        gameplayImageOpacityValue: document.getElementById('gameplay-image-opacity-value'),
        laneBackgroundOpacitySlider: document.getElementById('lane-background-opacity-slider'),
        laneBackgroundOpacityValue: document.getElementById('lane-background-opacity-value'),
        laneHighlightToggle: document.getElementById('lane-highlight-toggle'),
        autoHideUiToggle: document.getElementById('auto-hide-ui-toggle'),
        defaultFallSpeedToggle: document.getElementById('player-default-fallspeed-toggle'),
        defaultFallSpeedContainer: document.getElementById('player-default-fallspeed-container'),
        defaultFallSpeedSlider: document.getElementById('player-default-fallspeed-slider'),
        defaultFallSpeedValue: document.getElementById('player-default-fallspeed-value'),
        inputOffsetSlider: document.getElementById('input-offset-slider'),
        inputOffsetValue: document.getElementById('input-offset-value'),
        touchInputOffsetSlider: document.getElementById('touch-input-offset-slider'),
        touchInputOffsetValue: document.getElementById('touch-input-offset-value'),
        debugModeToggle: document.getElementById('debug-mode-toggle'),
        controls: {
            lanesSelector: document.getElementById('keybind-lanes-selector'),
            rowsContainer: document.getElementById('keybind-rows-container'),
            statusLabel: document.getElementById('keybind-status-label'),
            saveBtn: document.getElementById('save-keybinds-btn'),
            restartHotkeyBox: document.getElementById('restart-hotkey-box')
        },
        editorTab: {
            keybindRows: document.getElementById('editor-keybind-rows'),
            toolKeyRows: document.getElementById('editor-tool-keybind-rows'),
            statusLabel: document.getElementById('editor-keybind-status-label'),
            saveBtn: document.getElementById('save-editor-keybinds-btn'),
            resetBtn: document.getElementById('reset-editor-keybinds-btn'),
            defaultBpmInput: document.getElementById('editor-default-bpm'),
            defaultSnapSelect: document.getElementById('editor-default-snap'),
            defaultFallSpeedInput: document.getElementById('editor-default-fall-speed'),
            saveDefaultsBtn: document.getElementById('save-editor-defaults-btn'),
            resetDefaultsBtn: document.getElementById('reset-editor-defaults-btn'),
            defaultsStatusLabel: document.getElementById('editor-defaults-status-label'),
            gridStyleSelector: document.getElementById('editor-grid-style-selector'),
            gridStylePreview: document.getElementById('editor-grid-style-preview'),
        }
    },
    triggerModal: {
        container: document.getElementById('trigger-modal'),
        bpmInput: document.getElementById('trigger-bpm'),
        fallSpeedInput: document.getElementById('trigger-fall-speed'),
        transitionInput: document.getElementById('trigger-transition'),
        confirmBtn: document.getElementById('trigger-confirm-btn'),
        cancelBtn: document.getElementById('trigger-cancel-btn')
    }
};